import { AgentRun, BriefState, ContractEvent, Expectation, ExpectationEvent, MarketObservation, NormalityContract, Order, OrderDraft, SmartOrder, Watchlist, WatchlistItem } from '../models.js';
import { env } from '../config/env.js';
import { evaluatePaperOrders } from './orders.js'; import { evaluatePaperSmartOrders } from './smart-orders.js'; import { getHoldings, getPositions } from './portfolio.js';
import type { ClockContext } from '../shared/clock.js'; import { AppError } from '../shared/errors.js'; import { attentionFor } from './attention.js'; import { expectedVsActual } from './presentation.js';
const counts=(values:string[])=>values.reduce((a:Record<string,number>,x)=>(a[x]=(a[x]??0)+1,a),{});
const visibleContract=(c:any,clock:ClockContext)=>(c.resolution&&new Date(c.resolution.domainTimestamp)>clock.asOf)||(!c.resolution&&['SUPERSEDED','CANCELLED'].includes(c.status)&&new Date(c.updatedAt)>clock.asOf)?{...c,status:'ACTIVE',resolution:undefined}:c;
const visibleExpectation=(e:any,clock:ClockContext)=>(e.resolution&&new Date(e.resolution.resolvedAtDomainTime)>clock.asOf)||(!e.resolution&&['SUPERSEDED','CANCELLED'].includes(e.status)&&new Date(e.updatedAt)>clock.asOf)?{...e,status:'PENDING',resolution:undefined}:e;
export async function dashboardOverview(userId:string,clock:ClockContext,watchlistId?:string){
 await Promise.all([evaluatePaperOrders(clock,userId),evaluatePaperSmartOrders(clock,userId)]);
 const watchlists=await Watchlist.find({userId,...(watchlistId?{_id:watchlistId}:{})}).lean();if(watchlistId&&!watchlists.length)throw new AppError(404,'WATCHLIST_NOT_FOUND','Watchlist not found');const ids=watchlists.map(x=>x._id);const items:any[]=await WatchlistItem.find({watchlistId:{$in:ids}}).populate('instrumentId').lean();
 const [contractsRaw,expectationsRaw,states,orders,drafts,agentRuns,openSmartOrders,portfolio]=await Promise.all([NormalityContract.find({userId,watchlistId:{$in:ids},createdAtDomain:{$lte:clock.asOf}}).lean(),Expectation.find({userId,watchlistId:{$in:ids},'creationSnapshot.clock.asOf':{$lte:clock.asOf}}).lean(),BriefState.find({userId,$or:[{domainTimestamp:{$lte:clock.asOf}},{domainTimestamp:{$exists:false},updatedAt:{$lte:clock.asOf}}]}).lean(),Order.find({userId,submittedAt:{$lte:clock.asOf}}).sort({submittedAt:-1}).lean(),OrderDraft.countDocuments({userId,status:'AWAITING_CONFIRMATION',createdAt:{$lte:clock.asOf}}),AgentRun.find({userId,startedAt:{$lte:clock.asOf}}).sort({startedAt:-1}).limit(5).lean(),SmartOrder.countDocuments({userId,status:'ACTIVE',createdAt:{$lte:clock.asOf}}),Promise.all([getHoldings(userId).catch(()=>({holdings:[]})),getPositions(userId).catch(()=>({positions:[]}))])]);
 const contracts=contractsRaw.map(c=>visibleContract(c,clock));const expectations=expectationsRaw.map(e=>visibleExpectation(e,clock));const stateMap=new Map(states.map(x=>[String(x.expectationId),x.state]));const expectationAttention=expectations.map((e:any)=>{const p=expectedVsActual(e);const attention=attentionFor({status:e.status,outcome:e.resolution?.outcome,signalTypes:p.signalTypes,acknowledged:stateMap.get(String(e._id))==='ACKNOWLEDGED',gap:Math.abs(p.actual.relativePerformancePct??0)});return{expectationId:e._id,instrumentId:e.instrumentId,question:e.humanReadableQuestion,attention,signalTypes:p.signalTypes,status:e.status,outcome:e.resolution?.outcome,domainTimestamp:e.resolution?.resolvedAtDomainTime??e.creationSnapshot?.clock?.asOf};});
 const contractAttention=contracts.filter((c:any)=>c.resolution).map((c:any)=>{const signalTypes=(c.resolution?.signals??[]).flatMap((signal:any)=>signal.silentStory?[signal.signal,'SILENT_STORY']:[signal.signal]);return{contractId:c._id,instrumentId:c.instrumentId,question:'Did the sealed normality contract materially depart?',attention:attentionFor({status:c.status,signalTypes}),signalTypes,status:c.status,domainTimestamp:c.resolution?.domainTimestamp};});
 const attentionItems=[...expectationAttention,...contractAttention].sort((a,b)=>b.attention.score-a.attention.score);
 const latest=await Promise.all(items.map((item:any)=>MarketObservation.findOne({instrumentId:item.instrumentId._id,observedAt:{$lte:clock.asOf},availableAt:{$lte:clock.asOf}}).sort({observedAt:-1}).lean()));const freshness=counts(latest.map(x=>x?.freshness??'STALE'));const cc=counts(contracts.map((c:any)=>c.status));const ec=counts(expectations.map((e:any)=>e.resolution?.outcome??e.status));
 const orderCounts=counts(orders.map((order:any)=>String(order.status).toUpperCase()));
 return{clock,watchlistCount:watchlists.length,watchlistsCount:watchlists.length,watchedInstrumentCount:items.length,watchedInstrumentsCount:items.length,marketFreshness:{fresh:freshness.FRESH??0,delayed:freshness.DELAYED??0,stale:freshness.STALE??0},contracts:{active:(cc.ACTIVE??0)+(cc.PENDING_DATA??0),normal:cc.CLOSED_NORMAL??0,departed:cc.DEPARTED??0,unresolvable:cc.UNRESOLVABLE??0,expired:cc.EXPIRED_UNANSWERED??0},expectations:{pending:ec.PENDING??0,confirmed:ec.CONFIRMED??0,disconfirmed:ec.DISCONFIRMED??0,conditionNotMet:ec.CONDITION_NOT_MET??0,unscoreable:ec.UNSCOREABLE??0},attention:{high:attentionItems.filter(x=>x.attention.tier==='HIGH').length,medium:attentionItems.filter(x=>x.attention.tier==='MEDIUM').length,low:attentionItems.filter(x=>x.attention.tier==='LOW').length},topAttentionItems:attentionItems.slice(0,5),recentSilentStories:attentionItems.filter(x=>x.signalTypes.includes('SILENT_STORY')).sort((a,b)=>new Date(b.domainTimestamp).getTime()-new Date(a.domainTimestamp).getTime()).slice(0,5),unresolvableCount:cc.UNRESOLVABLE??0,returnBriefSummary:{total:expectations.length,unacknowledged:expectations.filter((e:any)=>stateMap.get(String(e._id))!=='ACKNOWLEDGED').length},recentAgentInvestigations:agentRuns,pendingOrderDrafts:drafts,openOrders:orders.filter((order:any)=>['OPEN','ACCEPTED','SUBMITTED'].includes(order.status)).length,openSmartOrders,portfolioSummary:{holdingsCount:portfolio[0].holdings.length,positionsCount:portfolio[1].positions.length},orders:{pendingDrafts:drafts,submitted:orders.length,filled:orderCounts.FILLED??0,failed:orderCounts.FAILED??0},recentOrders:orders.slice(0,10),tradingMode:env.TRADING_MODE,brokerProvider:env.BROKER_PROVIDER};
}
export async function dashboardHistory(userId:string,instrumentId:string,clock:ClockContext){
 const ids=(await Watchlist.find({userId}).select('_id').lean()).map(x=>x._id);const itemIds=(await WatchlistItem.find({watchlistId:{$in:ids},instrumentId}).select('_id').lean()).map(x=>x._id);if(!itemIds.length)throw new AppError(404,'INSTRUMENT_NOT_WATCHED','Instrument is not in an owned watchlist');
 const [bars,contracts,expectationsRaw]=await Promise.all([MarketObservation.find({instrumentId,observedAt:{$lte:clock.asOf},availableAt:{$lte:clock.asOf}}).sort({observedAt:1}).lean(),NormalityContract.find({userId,instrumentId,createdAtDomain:{$lte:clock.asOf}}).lean(),Expectation.find({userId,instrumentId,'creationSnapshot.clock.asOf':{$lte:clock.asOf}}).lean()]);const expectations:any[]=expectationsRaw;
 return{clock,priceSeries:bars.map(x=>({at:x.observedAt,value:x.adjustedClose??x.close??x.price,availableAt:x.availableAt})),volumeSeries:bars.filter(x=>x.volume!=null).map(x=>({at:x.observedAt,value:x.volume})),contractWindows:contracts.map(x=>({id:x._id,start:x.startTradingDate,end:x.deadlineTradingDate,status:visibleContract(x,clock).status})),expectationMarkers:expectations.map(x=>({id:x._id,at:x.creationSnapshot?.clock?.asOf,question:x.humanReadableQuestion})),resolutionMarkers:expectations.filter(x=>x.resolution?.resolvedAtDomainTime&&new Date(x.resolution.resolvedAtDomainTime)<=clock.asOf).map(x=>({id:x._id,at:x.resolution.resolvedAtDomainTime,outcome:x.resolution.outcome})),signalMarkers:contracts.flatMap((x:any)=>x.resolution&&new Date(x.resolution.domainTimestamp)<=clock.asOf?(x.resolution.signals??[]).map((s:any)=>({...s,contractId:x._id})):[])};
}
export async function dashboardWatchlist(userId:string,watchlistId:string,clock:ClockContext){const watchlist=await Watchlist.findOne({_id:watchlistId,userId}).lean();if(!watchlist)throw new AppError(404,'WATCHLIST_NOT_FOUND','Watchlist not found');const items:any[]=await WatchlistItem.find({watchlistId}).populate('instrumentId').lean();const rows=await Promise.all(items.map(async item=>{const [quote,contractRaw,expectationsRaw,latestContractEvent,latestExpectationEvent]=await Promise.all([MarketObservation.findOne({instrumentId:item.instrumentId._id,observedAt:{$lte:clock.asOf},availableAt:{$lte:clock.asOf}}).sort({observedAt:-1}).lean(),NormalityContract.findOne({userId,watchlistItemId:item._id,createdAtDomain:{$lte:clock.asOf}}).sort({createdAtDomain:-1}).lean(),Expectation.find({userId,watchlistItemId:item._id,'creationSnapshot.clock.asOf':{$lte:clock.asOf}}).sort({'creationSnapshot.clock.asOf':1}).lean(),ContractEvent.findOne({userId,watchlistId,instrumentId:item.instrumentId._id,availableAt:{$lte:clock.asOf}}).sort({domainTimestamp:-1,recordedAt:-1}).lean(),ExpectationEvent.findOne({userId,watchlistId,instrumentId:item.instrumentId._id,availableAt:{$lte:clock.asOf}}).sort({domainTimestamp:-1,recordedAt:-1}).lean()]);const contract=contractRaw?visibleContract(contractRaw,clock):null;const expectations=expectationsRaw.map(e=>visibleExpectation(e,clock));const latest=expectations.at(-1);const presentation=latest?expectedVsActual(latest):null;const attention=latest?attentionFor({status:latest.status,outcome:latest.resolution?.outcome,signalTypes:presentation?.signalTypes}):attentionFor({status:contract?.status??'ACTIVE'});const eventCandidates=[latestContractEvent,latestExpectationEvent].filter(Boolean) as any[];const latestEvent=eventCandidates.sort((a,b)=>new Date(b.domainTimestamp).getTime()-new Date(a.domainTimestamp).getTime())[0];return{watchlistItem:item,instrument:item.instrumentId,quote:quote?{price:quote.price,dayChangePct:quote.dayChangePct,observedAt:quote.observedAt,availableAt:quote.availableAt,freshness:quote.freshness,provider:quote.provider}:null,contract:contract?{id:contract._id,status:contract.status,deadline:contract.deadlineTradingDate,dataQuality:contract.dataQualityAtCreation}:null,expectations:{count:expectations.length,pending:expectations.filter((e:any)=>e.status==='PENDING').length,latest:latest?{id:latest._id,status:latest.status,outcome:latest.resolution?.outcome}:null},attention,latestMeaningfulEvent:latestEvent?{type:latestEvent.type,domainTimestamp:latestEvent.domainTimestamp,evidence:latestEvent.evidence}:null,latestSignal:contract?.resolution?.signals?.at(-1)??presentation?.signalTypes?.at(-1)??null};}));return{clock,watchlist,rows};}
