import { Types } from 'mongoose'; import { Expectation, ExpectationEvent, Instrument, MarketObservation, Watchlist, WatchlistItem } from '../models.js'; import type { ClockContext } from '../shared/clock.js'; import { AppError } from '../shared/errors.js'; import { TradingCalendar } from '../shared/trading-calendar.js';
type Obs = any;
export async function ownedWatchlist(userId: string, id: string) { const w = await Watchlist.findOne({ _id: id, userId }); if (!w) throw new AppError(404, 'WATCHLIST_NOT_FOUND', 'Watchlist not found'); return w; }
export async function ownedItem(userId: string, watchlistId: string, itemId: string) { await ownedWatchlist(userId, watchlistId); const item = await WatchlistItem.findOne({ _id: itemId, watchlistId }); if (!item) throw new AppError(404, 'WATCHLIST_ITEM_NOT_FOUND', 'Watchlist item not found'); return item; }
export const admissibleFilter = (instrumentId: unknown, clock: ClockContext, start?: Date) => ({ instrumentId, observedAt: start ? { $gte: start, $lte: clock.asOf } : { $lte: clock.asOf }, availableAt: { $lte: clock.asOf } });
export async function admissibleLatest(instrumentId: unknown, clock: ClockContext): Promise<Obs> { const o = await MarketObservation.findOne(admissibleFilter(instrumentId, clock)).sort({ observedAt: -1, ingestedAt: -1 }).lean(); if (!o) throw new AppError(422, 'MARKET_DATA_MISSING', 'No market observation admissible for this clock'); return o; }
export async function admissibleBars(instrumentId: unknown, start: Date, clock: ClockContext) { return MarketObservation.find(admissibleFilter(instrumentId, clock, start)).sort({ observedAt: 1, ingestedAt: 1 }).lean(); }
const safe = (o: Obs) => o.adjustmentStatus === 'SAFE' && o.freshness !== 'STALE';
const pct = (a: number, b: number) => ((b - a) / a) * 100;
export async function createExpectation(userId: string, watchlistId: string, itemId: string, input: any, clock: ClockContext, calendar: TradingCalendar, sourceIntentId?: string) {
  const item = await ownedItem(userId, watchlistId, itemId); const instrument = await Instrument.findById(item.instrumentId).lean(); if (!instrument) throw new AppError(404, 'INSTRUMENT_NOT_FOUND', 'Instrument not found');
  const days = input.deadlineTradingDays; const deadline = calendar.addTradingDays(clock.asOf, days); const base = await admissibleLatest(instrument._id, clock); let benchmark: any; if (input.benchmarkInstrumentId) { benchmark = await admissibleLatest(new Types.ObjectId(input.benchmarkInstrumentId), clock); }
  const question = input.template === 'RELATIVE_OUTPERFORMANCE' ? `Will ${instrument.symbol} outperform its benchmark by at least ${input.minimumOutperformancePct}% over ${days} trading days?` : input.template === 'PRICE_THRESHOLD' ? `Will ${instrument.symbol} close ${input.direction.toLowerCase()} ${input.threshold} within ${days} trading days?` : `If the benchmark gains ${input.benchmarkTriggerPct}%, will ${instrument.symbol} participate by ${input.minimumParticipationRatio}?`;
  const expectation = await Expectation.create({ userId, watchlistId, watchlistItemId: item._id, instrumentId: instrument._id, sourceIntentId, template: input.template, parameters: input, humanReadableQuestion: question, recordedAt: new Date(), deadlineTradingDays: days, deadlineTradingDate: deadline, status: 'PENDING', creationSnapshot: { clock: { mode: clock.mode, asOf: clock.asOf }, instrument: base, benchmark, templateInputs: input }, createdFromClockMode: clock.mode });
  await recordExpectationEvent(expectation, 'EXPECTATION_CREATED', clock, { question, deadlineTradingDate: deadline, creationSnapshot: expectation.creationSnapshot });
  return expectation;
}
export async function resolveExpectation(userId: string, id: string, clock: ClockContext) {
  const e: any = await Expectation.findOne({ _id: id, userId }); if (!e) throw new AppError(404, 'EXPECTATION_NOT_FOUND', 'Expectation not found'); if (e.status !== 'PENDING') return e; if (clock.asOf < e.deadlineTradingDate) throw new AppError(409, 'DEADLINE_NOT_REACHED', 'Expectation deadline has not been reached');
  const start = e.creationSnapshot.clock.asOf; const bars = await admissibleBars(e.instrumentId, start, { ...clock, asOf: e.deadlineTradingDate }); const last = bars.at(-1); const p = e.parameters; const base = e.creationSnapshot.instrument;
  if (!last || !safe(base) || !safe(last)) { e.status = 'UNSCOREABLE'; e.resolution = { resolvedAtDomainTime: clock.asOf, recordedAt: new Date(), measurement: {}, evidence: { reason: 'Adjustment-safe, fresh market evidence is unavailable' }, reason: 'Evidence is insufficient for a safe comparison', clockMode: clock.mode }; await e.save(); await recordExpectationEvent(e, 'EXPECTATION_UNSCOREABLE', clock, e.resolution); return e; }
  const ending = Number(last.close ?? last.price); let outcome: string; let measurement: any = { startPrice: base.price, endPrice: ending, instrumentReturnPct: pct(Number(base.price), ending) };
  if (e.template === 'PRICE_THRESHOLD') outcome = p.direction === 'ABOVE' ? (bars.some((b: Obs) => (b.close ?? b.price) > p.threshold) ? 'CONFIRMED' : 'DISCONFIRMED') : (bars.some((b: Obs) => (b.close ?? b.price) < p.threshold) ? 'CONFIRMED' : 'DISCONFIRMED');
  else { const benchBars = await admissibleBars(e.creationSnapshot.benchmark.instrumentId, start, { ...clock, asOf: e.deadlineTradingDate }); const bLast = benchBars.at(-1); const bBase = e.creationSnapshot.benchmark; if (!bLast || !safe(bBase) || !safe(bLast)) { e.status = 'UNSCOREABLE'; e.resolution = { resolvedAtDomainTime: clock.asOf, recordedAt: new Date(), measurement: {}, evidence: {}, reason: 'Benchmark evidence is insufficient for a safe comparison', clockMode: clock.mode }; await e.save(); await recordExpectationEvent(e, 'EXPECTATION_UNSCOREABLE', clock, e.resolution); return e; } const br = pct(Number(bBase.price), Number(bLast.close ?? bLast.price)); measurement.benchmarkReturnPct = br;
    if (e.template === 'RELATIVE_OUTPERFORMANCE') { measurement.relativePerformancePct = measurement.instrumentReturnPct - br; outcome = measurement.relativePerformancePct >= p.minimumOutperformancePct ? 'CONFIRMED' : 'DISCONFIRMED'; }
    else { const triggerBar=benchBars.find((b:Obs)=>safe(b)&&pct(Number(bBase.price),Number(b.close??b.price))>=p.benchmarkTriggerPct);if(!triggerBar)outcome='CONDITION_NOT_MET';else{const triggerReturn=pct(Number(bBase.price),Number(triggerBar.close??triggerBar.price));const stockAtTrigger=[...bars].reverse().find((b:Obs)=>safe(b)&&new Date(b.observedAt)<=new Date(triggerBar.observedAt));measurement.triggerObservedAt=triggerBar.observedAt;measurement.benchmarkReturnAtTrigger=triggerReturn;measurement.stockValueAtTrigger=stockAtTrigger?Number(stockAtTrigger.close??stockAtTrigger.price):undefined;measurement.participationRatio=triggerReturn===0?0:measurement.instrumentReturnPct/triggerReturn;outcome=measurement.participationRatio>=p.minimumParticipationRatio?'CONFIRMED':'DISCONFIRMED';} }
  }
  e.status = 'RESOLVED'; e.resolution = { resolvedAtDomainTime: clock.asOf, recordedAt: new Date(), outcome, measurement, evidence: { instrument: last, creationSnapshot: e.creationSnapshot }, reason: 'Resolved from admissible market observations without causal attribution', clockMode: clock.mode }; await e.save(); await recordExpectationEvent(e, 'EXPECTATION_RESOLVED', clock, e.resolution); return e;
}

export async function recordExpectationEvent(expectation:any,type:string,clock:ClockContext,evidence?:any){
  return ExpectationEvent.create({userId:expectation.userId,expectationId:expectation._id,instrumentId:expectation.instrumentId,watchlistId:expectation.watchlistId,type,domainTimestamp:clock.asOf,recordedAt:new Date(),availableAt:clock.asOf,evidence});
}
