import crypto from 'node:crypto';
import { AuditEvent, Instrument, MarketObservation, Order, OrderDraft, OrderEvent, PaperHolding, PaperTrade, SmartOrder } from '../models.js';
import { env } from '../config/env.js';
import { AppError } from '../shared/errors.js';
import type { ClockContext } from '../shared/clock.js';

export type NormalizedOrderRequest={instrumentId:string;tradingSymbol:string;exchange:'NSE';segment:'CASH';product:'CNC';transactionType:'BUY'|'SELL';quantity:number;orderType:'MARKET'|'LIMIT';price?:number;triggerPrice?:number;validity:'DAY';referenceId:string;quote?:any};
export interface BrokerExecutionProvider{
  createOrder(input:NormalizedOrderRequest):Promise<any>;cancelOrder(order:any):Promise<any>;getOrder(order:any):Promise<any>;listOrders(userId:string):Promise<any[]>;getTrades(order:any):Promise<any[]>;getHoldings(userId:string):Promise<any[]>;getPositions(userId:string):Promise<any[]>;
  createSmartOrder(input:any):Promise<any>;getSmartOrder(order:any):Promise<any>;listSmartOrders(userId:string):Promise<any[]>;cancelSmartOrder(order:any):Promise<any>;
}
const canonical=(value:Record<string,unknown>)=>JSON.stringify(Object.keys(value).sort().reduce((out:any,key)=>(out[key]=value[key],out),{}));
const hash=(value:string)=>crypto.createHash('sha256').update(value).digest('hex');
const modeFor=(requested?:string)=>requested??env.TRADING_MODE;
const currentQuote=(instrumentId:unknown,clock:ClockContext={mode:'LIVE',asOf:new Date()})=>MarketObservation.findOne({instrumentId,observedAt:{$lte:clock.asOf},availableAt:{$lte:clock.asOf}}).sort({observedAt:-1,ingestedAt:-1}).lean();
const draftPayload=(draft:any)=>({instrumentId:String(draft.instrumentId),tradingSymbol:draft.symbol,exchange:draft.exchange,segment:draft.segment,product:draft.product,transactionType:draft.transactionType,quantity:Number(draft.quantity),orderType:draft.orderType,price:draft.price??null,triggerPrice:draft.triggerPrice??null,validity:draft.validity,mode:draft.mode,source:draft.source});
const liveGate=(userId:string)=>{if(env.TRADING_MODE!=='LIVE'||!env.LIVE_TRADING_ENABLED)throw new AppError(403,'LIVE_TRADING_DISABLED','Live trading is disabled');if(env.BROKER_PROVIDER!=='GROWW')throw new AppError(409,'LIVE_BROKER_REQUIRED','Live trading requires the Groww broker provider');const allow=env.LIVE_TRADING_USER_ALLOWLIST.split(',').map(x=>x.trim()).filter(Boolean);if(allow.length&&!allow.includes(userId))throw new AppError(403,'LIVE_TRADING_NOT_ALLOWED','User is not permitted for live trading');};

export class PaperBrokerProvider implements BrokerExecutionProvider{
  async createOrder(input:NormalizedOrderRequest){const quote=Number(input.quote?.price);const executable=input.orderType==='MARKET'||(input.transactionType==='BUY'?quote<=Number(input.price):quote>=Number(input.price));return{brokerOrderId:`paper_${input.referenceId}`,referenceId:input.referenceId,status:executable?'FILLED':'OPEN',filledQuantity:executable?input.quantity:0,averageFillPrice:executable?quote:undefined,mode:'PAPER'};}
  async cancelOrder(order:any){return{...order,status:order.status==='OPEN'?'CANCELLED':order.status,mode:'PAPER'};} async getOrder(order:any){return order;} async listOrders(userId:string){return Order.find({userId,mode:'PAPER'}).sort({submittedAt:-1}).lean();} async getTrades(order:any){return PaperTrade.find({orderId:order._id,userId:order.userId}).lean();} async getHoldings(userId:string){return PaperHolding.find({userId,quantity:{$gt:0}}).lean();} async getPositions(userId:string){return this.getHoldings(userId);}
  async createSmartOrder(input:any){return{brokerSmartOrderId:`paper_gtt_${input.referenceId}`,referenceId:input.referenceId,status:'ACTIVE',mode:'PAPER'};} async getSmartOrder(order:any){return order;} async listSmartOrders(userId:string){return SmartOrder.find({userId,mode:'PAPER'}).lean();} async cancelSmartOrder(order:any){return{...order,status:'CANCELLED',mode:'PAPER'};}
}

export class GrowwBrokerProvider implements BrokerExecutionProvider{
  private async call(path:string,method='GET',body?:unknown){if(!env.GROWW_ACCESS_TOKEN)throw new AppError(503,'BROKER_NOT_CONFIGURED','Groww is not configured');let response:Response;try{response=await fetch(`${env.GROWW_API_BASE_URL}${path}`,{method,headers:{Authorization:`Bearer ${env.GROWW_ACCESS_TOKEN}`,Accept:'application/json','X-API-VERSION':'1.0',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});}catch{throw new AppError(502,'BROKER_UNAVAILABLE','Groww broker request failed');}if(!response.ok)throw new AppError(502,'BROKER_ERROR','Groww broker returned an error');const raw:any=await response.json();return raw.payload??raw.data??raw;}
  async createOrder(i:NormalizedOrderRequest){const x:any=await this.call('/order/create','POST',{trading_symbol:i.tradingSymbol,quantity:i.quantity,price:i.price,trigger_price:i.triggerPrice,validity:i.validity,exchange:i.exchange,segment:i.segment,product:i.product,order_type:i.orderType,transaction_type:i.transactionType,order_reference_id:i.referenceId});return{brokerOrderId:x.groww_order_id??x.order_id,status:String(x.order_status??x.status??'SUBMITTED').toUpperCase(),referenceId:i.referenceId,raw:x};}
  async cancelOrder(o:any){const x:any=await this.call('/order/cancel','POST',{groww_order_id:o.brokerOrderId,segment:o.segment??'CASH'});return{status:String(x.order_status??x.status??'CANCELLED').toUpperCase(),raw:x};} async getOrder(o:any){return this.call(`/order/status/${encodeURIComponent(o.brokerOrderId)}`);} async listOrders(_userId:string){const x:any=await this.call('/orders');return Array.isArray(x)?x:x.orders??[];} async getTrades(o:any){const x:any=await this.call(`/trades?groww_order_id=${encodeURIComponent(o.brokerOrderId)}`);return Array.isArray(x)?x:x.trades??[];} async getHoldings(_userId:string){const x:any=await this.call('/holdings');return Array.isArray(x)?x:x.holdings??[];} async getPositions(_userId:string){const x:any=await this.call('/positions');return Array.isArray(x)?x:x.positions??[];}
  async createSmartOrder(i:any){const x:any=await this.call('/smart-order/create','POST',{trading_symbol:i.symbol,exchange:'NSE',segment:'CASH',product:'CNC',transaction_type:i.transactionType,quantity:i.quantity,trigger_price:i.triggerPrice,trigger_direction:i.triggerDirection,order_type:i.postTriggerOrderType,price:i.postTriggerPrice,reference_id:i.referenceId});return{brokerSmartOrderId:x.smart_order_id??x.gtt_order_id,status:String(x.status??'ACTIVE').toUpperCase(),raw:x};} async getSmartOrder(o:any){return this.call(`/smart-order/${encodeURIComponent(o.brokerSmartOrderId)}`);} async listSmartOrders(_userId:string){const x:any=await this.call('/smart-orders');return Array.isArray(x)?x:x.smart_orders??[];} async cancelSmartOrder(o:any){const x:any=await this.call('/smart-order/cancel','POST',{smart_order_id:o.brokerSmartOrderId});return{status:String(x.status??'CANCELLED').toUpperCase(),raw:x};}
}

export const brokerForMode=(mode:string):BrokerExecutionProvider=>mode==='LIVE'?new GrowwBrokerProvider():new PaperBrokerProvider();
async function orderEvent(userId:string,type:string,orderId?:unknown,draftId?:unknown,metadata?:any){return OrderEvent.create({userId,orderId,draftId,type,recordedAt:new Date(),metadata});}
async function audit(userId:string,type:string,entityType:string,entityId:unknown,metadata?:any){return AuditEvent.create({userId,type,entityType,entityId,timestamp:new Date(),metadata});}
export async function validateSellEligibility(userId:string,instrumentId:unknown,quantity:number,mode:string,symbol?:string){const holdings:any[]=mode==='PAPER'?await PaperHolding.find({userId,instrumentId,quantity:{$gt:0}}).lean():await brokerForMode(mode).getHoldings(userId);const available=holdings.filter((h:any)=>String(h.instrumentId??h.instrument_id??'')===String(instrumentId)||Boolean(symbol)&&String(h.trading_symbol??h.symbol??'').toUpperCase()===String(symbol).toUpperCase()).reduce((sum:number,h:any)=>sum+Number(h.quantity??h.available_quantity??0),0);if(available<quantity)throw new AppError(409,'INSUFFICIENT_HOLDINGS','SELL quantity exceeds available holdings');}

export async function createDraft(userId:string,input:any,clock:ClockContext={mode:'LIVE',asOf:new Date()}){
  if(clock.mode==='REPLAY')throw new AppError(403,'TRADING_DISABLED_IN_REPLAY','Trading actions are disabled in replay');const mode=modeFor(input.mode);if(mode==='LIVE')liveGate(userId);const instrument:any=await Instrument.findOne({_id:input.instrumentId,active:true}).lean();if(!instrument)throw new AppError(404,'INSTRUMENT_NOT_FOUND','Instrument not found');if(input.quantity>env.LIVE_MAX_ORDER_QUANTITY)throw new AppError(400,'ORDER_QUANTITY_LIMIT','Quantity exceeds configured limit');const quote:any=await currentQuote(instrument._id,clock);if(!quote||quote.freshness==='STALE')throw new AppError(409,'FRESH_QUOTE_REQUIRED','A fresh quote is required');const estimatedNotional=input.quantity*Number(input.price??quote.price);if(estimatedNotional>env.LIVE_MAX_ORDER_NOTIONAL)throw new AppError(400,'ORDER_NOTIONAL_LIMIT','Notional exceeds configured limit');const token=crypto.randomBytes(24).toString('base64url');const terms={instrumentId:instrument._id,symbol:instrument.symbol,exchange:'NSE',transactionType:input.transactionType,side:input.transactionType,quantity:input.quantity,orderType:input.orderType,price:input.price,triggerPrice:input.triggerPrice,product:'CNC',segment:'CASH',validity:'DAY',mode,source:input.source??'DIRECT_API'};const draft=await OrderDraft.create({userId,...terms,quoteSnapshot:{price:quote.price,observedAt:quote.observedAt,availableAt:quote.availableAt},estimatedNotional,expiresAt:new Date(Date.now()+env.ORDER_CONFIRMATION_TTL_SECONDS*1000),confirmationNonceHash:hash(token),payloadHash:hash(canonical(draftPayload(terms))),idempotencyReference:crypto.randomUUID()});await Promise.all([orderEvent(userId,'ORDER_DRAFT_CREATED',undefined,draft._id),orderEvent(userId,'ORDER_CONFIRMATION_REQUIRED',undefined,draft._id),audit(userId,'ORDER_DRAFT_CREATED','ORDER_DRAFT',draft._id,{mode,source:terms.source})]);return{draft,confirmationToken:token,summary:{symbol:draft.symbol,side:draft.transactionType,quantity:draft.quantity,orderType:draft.orderType,price:draft.price,estimatedNotional,mode}};
}

export async function confirmDraft(userId:string,id:string,token:string){
  const draft:any=await OrderDraft.findOne({_id:id,userId});if(!draft)throw new AppError(404,'ORDER_DRAFT_NOT_FOUND','Order draft not found');const existing=await Order.findOne({draftId:draft._id});if(existing)return existing;if(draft.status!=='AWAITING_CONFIRMATION')throw new AppError(409,'ORDER_DRAFT_NOT_CONFIRMABLE','Draft is not confirmable');if(draft.expiresAt<new Date()){draft.status='EXPIRED';await draft.save();throw new AppError(409,'ORDER_DRAFT_EXPIRED','Order draft expired');}if(hash(token)!==draft.confirmationNonceHash)throw new AppError(401,'INVALID_CONFIRMATION_TOKEN','Confirmation token is invalid');if(hash(canonical(draftPayload(draft)))!==draft.payloadHash)throw new AppError(409,'ORDER_DRAFT_CHANGED','Order fields changed after preview');if(draft.mode==='LIVE')liveGate(userId);if(draft.quantity>env.LIVE_MAX_ORDER_QUANTITY||draft.estimatedNotional>env.LIVE_MAX_ORDER_NOTIONAL)throw new AppError(409,'ORDER_LIMIT_CHANGED','Order exceeds current safety limits');if(draft.transactionType==='SELL')await validateSellEligibility(userId,draft.instrumentId,draft.quantity,draft.mode,draft.symbol);const quote:any=await currentQuote(draft.instrumentId);if(!quote||quote.freshness==='STALE')throw new AppError(409,'FRESH_QUOTE_REQUIRED','A fresh quote is required');const drift=Math.abs((Number(quote.price)-Number(draft.quoteSnapshot.price))/Number(draft.quoteSnapshot.price))*100;if(drift>env.ORDER_REQUOTE_THRESHOLD_PCT){const refreshedToken=crypto.randomBytes(24).toString('base64url');draft.quoteSnapshot={price:quote.price,observedAt:quote.observedAt,availableAt:quote.availableAt};draft.estimatedNotional=draft.quantity*Number(draft.price??quote.price);draft.expiresAt=new Date(Date.now()+env.ORDER_CONFIRMATION_TTL_SECONDS*1000);draft.confirmationNonceHash=hash(refreshedToken);await draft.save();await orderEvent(userId,'ORDER_RECONFIRM_REQUIRED',undefined,draft._id,{driftPct:drift});throw new AppError(409,'ORDER_RECONFIRM_REQUIRED','Quote changed beyond the configured threshold',{draftId:draft._id,confirmationToken:refreshedToken,quoteSnapshot:draft.quoteSnapshot,estimatedNotional:draft.estimatedNotional});}
  draft.status='CONFIRMED';await draft.save();await Promise.all([orderEvent(userId,'ORDER_CONFIRMED',undefined,draft._id),audit(userId,'ORDER_CONFIRMED','ORDER_DRAFT',draft._id,{mode:draft.mode})]);const request:NormalizedOrderRequest={instrumentId:String(draft.instrumentId),tradingSymbol:draft.symbol,exchange:'NSE',segment:'CASH',product:'CNC',transactionType:draft.transactionType,quantity:draft.quantity,orderType:draft.orderType,price:draft.price,triggerPrice:draft.triggerPrice,validity:'DAY',referenceId:draft.idempotencyReference,quote};
  try{const result=await brokerForMode(draft.mode).createOrder(request);const order=await Order.findOneAndUpdate({draftId:draft._id},{$setOnInsert:{userId,draftId:draft._id,provider:draft.mode==='LIVE'?'GROWW':'PAPER',brokerOrderId:result.brokerOrderId,referenceId:draft.idempotencyReference,instrument:{id:draft.instrumentId,symbol:draft.symbol,exchange:draft.exchange},side:draft.transactionType,quantity:draft.quantity,orderType:draft.orderType,price:draft.price,triggerPrice:draft.triggerPrice,product:draft.product,segment:draft.segment,validity:draft.validity,mode:draft.mode,status:result.status,filledQuantity:result.filledQuantity??0,averageFillPrice:result.averageFillPrice,submittedAt:new Date(),updatedBrokerAt:new Date()}},{upsert:true,new:true,setDefaultsOnInsert:true});draft.status='EXECUTED';await draft.save();await orderEvent(userId,'ORDER_SUBMITTED',order._id,draft._id,{provider:order.provider});await audit(userId,'ORDER_SUBMITTED','ORDER',order._id,{provider:order.provider,mode:order.mode});if(['OPEN','ACCEPTED','SUBMITTED'].includes(order.status))await orderEvent(userId,'BROKER_ACCEPTED',order._id,draft._id);if(order.status==='FILLED'){await orderEvent(userId,'FILLED',order._id,draft._id,{filledQuantity:order.filledQuantity,averageFillPrice:order.averageFillPrice});if(order.mode==='PAPER')await applyPaperFill(order);}return order;}catch(error){draft.status='FAILED';await draft.save();await orderEvent(userId,'FAILED',undefined,draft._id);throw error;}
}

export async function applyPaperFill(order:any){if(await PaperTrade.exists({orderId:order._id}))return;const instrumentId=order.instrument?.id;let holding:any=await PaperHolding.findOne({userId:order.userId,instrumentId});const quantity=Number(order.filledQuantity??order.quantity),price=Number(order.averageFillPrice);if(order.side==='SELL'&&(!holding||holding.quantity<quantity))throw new AppError(409,'INSUFFICIENT_HOLDINGS','SELL quantity exceeds paper holdings');if(!holding)holding=new PaperHolding({userId:order.userId,instrumentId,symbol:order.instrument.symbol,quantity:0,averagePrice:0,realizedPnl:0});if(order.side==='BUY'){holding.averagePrice=((holding.quantity*holding.averagePrice)+(quantity*price))/(holding.quantity+quantity);holding.quantity+=quantity;}else{holding.quantity-=quantity;holding.realizedPnl+=(price-holding.averagePrice)*quantity;if(holding.quantity===0)holding.averagePrice=0;}await holding.save();await PaperTrade.create({userId:order.userId,orderId:order._id,instrumentId,symbol:order.instrument.symbol,side:order.side,quantity,price,executedAt:new Date()});}

export async function evaluatePaperOrders(clock:ClockContext={mode:'LIVE',asOf:new Date()},userId?:string){if(clock.mode==='REPLAY')return[];const open:any[]=await Order.find({mode:'PAPER',status:'OPEN',...(userId?{userId}:{})});const filled:any[]=[];for(const order of open){const quote:any=await currentQuote(order.instrument.id,clock);if(!quote||quote.freshness==='STALE')continue;const hit=order.orderType==='LIMIT'&&(order.side==='BUY'?Number(quote.price)<=Number(order.price):Number(quote.price)>=Number(order.price));if(!hit)continue;order.status='FILLED';order.filledQuantity=order.quantity;order.averageFillPrice=quote.price;order.updatedBrokerAt=new Date();await order.save();await orderEvent(String(order.userId),'FILLED',order._id,order.draftId,{filledQuantity:order.quantity,averageFillPrice:quote.price});await applyPaperFill(order);filled.push(order);}return filled;}

export async function cancelOrder(userId:string,id:string){const order:any=await Order.findOne({_id:id,userId});if(!order)throw new AppError(404,'ORDER_NOT_FOUND','Order not found');if(!['OPEN','ACCEPTED','SUBMITTED'].includes(order.status))throw new AppError(409,'ORDER_NOT_CANCELLABLE','Order is not cancellable');await orderEvent(userId,'CANCEL_REQUESTED',order._id,order.draftId);const result=await brokerForMode(order.mode).cancelOrder(order);order.status=result.status??'CANCELLED';order.updatedBrokerAt=new Date();await order.save();await Promise.all([orderEvent(userId,'CANCELLED',order._id,order.draftId),audit(userId,'ORDER_CANCELLED','ORDER',order._id,{mode:order.mode})]);return order;}

export async function refreshOrder(userId:string,id:string){const order:any=await Order.findOne({_id:id,userId});if(!order)throw new AppError(404,'ORDER_NOT_FOUND','Order not found');if(order.mode==='PAPER'){await evaluatePaperOrders({mode:'LIVE',asOf:new Date()},userId);return Order.findById(order._id).lean();}const result:any=await brokerForMode('LIVE').getOrder(order);const status=String(result.order_status??result.status??order.status).toUpperCase();if(status!==order.status){order.status=status;order.filledQuantity=result.filled_quantity??order.filledQuantity;order.averageFillPrice=result.average_price??order.averageFillPrice;order.updatedBrokerAt=new Date();await order.save();await orderEvent(userId,status==='FILLED'?'FILLED':status==='REJECTED'?'REJECTED':'BROKER_ACCEPTED',order._id,order.draftId);}return order;}
