import crypto from 'node:crypto';
import { AuditEvent, Instrument, MarketObservation, Order, OrderEvent, PaperHolding, SmartOrder, SmartOrderDraft, SmartOrderEvent } from '../models.js';
import { env } from '../config/env.js';
import type { ClockContext } from '../shared/clock.js';
import { AppError } from '../shared/errors.js';
import { applyPaperFill, brokerForMode, validateSellEligibility } from './orders.js';

const hash=(value:string)=>crypto.createHash('sha256').update(value).digest('hex');
const canonical=(value:Record<string,unknown>)=>JSON.stringify(Object.keys(value).sort().reduce((out:any,key)=>(out[key]=value[key],out),{}));
const terms=(draft:any)=>({instrumentId:String(draft.instrumentId),symbol:draft.symbol,exchange:draft.exchange,transactionType:draft.transactionType,quantity:Number(draft.quantity),triggerPrice:Number(draft.triggerPrice),triggerDirection:draft.triggerDirection,postTriggerOrderType:draft.postTriggerOrderType,postTriggerPrice:draft.postTriggerPrice??null,product:draft.product,segment:draft.segment,mode:draft.mode,source:draft.source,validUntil:draft.validUntil?new Date(draft.validUntil).toISOString():null});
const event=(userId:string,type:string,smartOrderId?:unknown,draftId?:unknown,metadata?:any)=>SmartOrderEvent.create({userId,type,smartOrderId,draftId,recordedAt:new Date(),metadata});
const audit=(userId:string,type:string,entityType:string,entityId:unknown,metadata?:any)=>AuditEvent.create({userId,type,entityType,entityId,timestamp:new Date(),metadata});
const liveGate=(userId:string)=>{if(env.TRADING_MODE!=='LIVE'||!env.LIVE_TRADING_ENABLED)throw new AppError(403,'LIVE_TRADING_DISABLED','Live trading is disabled');if(env.BROKER_PROVIDER!=='GROWW')throw new AppError(409,'LIVE_BROKER_REQUIRED','Live smart orders require Groww');const allow=env.LIVE_TRADING_USER_ALLOWLIST.split(',').map(x=>x.trim()).filter(Boolean);if(allow.length&&!allow.includes(userId))throw new AppError(403,'LIVE_TRADING_NOT_ALLOWED','User is not permitted for live trading');};

export async function createSmartOrderDraft(userId:string,input:any,clock:ClockContext={mode:'LIVE',asOf:new Date()}){
  if(clock.mode==='REPLAY')throw new AppError(403,'TRADING_DISABLED_IN_REPLAY','Trading actions are disabled in replay');const mode=input.mode??env.TRADING_MODE;if(mode==='LIVE')liveGate(userId);if(input.quantity>env.LIVE_MAX_ORDER_QUANTITY)throw new AppError(400,'ORDER_QUANTITY_LIMIT','Quantity exceeds configured limit');const instrument:any=await Instrument.findOne({_id:input.instrumentId,active:true}).lean();if(!instrument)throw new AppError(404,'INSTRUMENT_NOT_FOUND','Instrument not found');const quote:any=await MarketObservation.findOne({instrumentId:instrument._id,observedAt:{$lte:clock.asOf},availableAt:{$lte:clock.asOf}}).sort({observedAt:-1}).lean();if(!quote||quote.freshness==='STALE')throw new AppError(409,'FRESH_QUOTE_REQUIRED','A fresh quote is required');const token=crypto.randomBytes(24).toString('base64url');const data={instrumentId:instrument._id,symbol:instrument.symbol,exchange:'NSE',transactionType:input.transactionType,quantity:input.quantity,triggerPrice:input.triggerPrice,triggerDirection:input.triggerDirection,postTriggerOrderType:input.postTriggerOrderType,postTriggerPrice:input.postTriggerPrice,product:'CNC',segment:'CASH',mode,source:input.source??'DIRECT_API',validUntil:input.expiresAt};const draft=await SmartOrderDraft.create({userId,...data,quoteSnapshot:{price:quote.price,observedAt:quote.observedAt,availableAt:quote.availableAt},expiresAt:new Date(Date.now()+env.ORDER_CONFIRMATION_TTL_SECONDS*1000),confirmationNonceHash:hash(token),payloadHash:hash(canonical(terms(data))),idempotencyReference:crypto.randomUUID()});await Promise.all([event(userId,'GTT_DRAFT_CREATED',undefined,draft._id),event(userId,'GTT_CONFIRMATION_REQUIRED',undefined,draft._id),audit(userId,'GTT_DRAFT_CREATED','SMART_ORDER_DRAFT',draft._id,{mode,source:data.source})]);return{draft,confirmationToken:token,summary:{symbol:draft.symbol,side:draft.transactionType,quantity:draft.quantity,triggerDirection:draft.triggerDirection,triggerPrice:draft.triggerPrice,postTriggerOrderType:draft.postTriggerOrderType,postTriggerPrice:draft.postTriggerPrice,mode}};
}

export async function confirmSmartOrderDraft(userId:string,id:string,token:string){
  const draft:any=await SmartOrderDraft.findOne({_id:id,userId});if(!draft)throw new AppError(404,'GTT_DRAFT_NOT_FOUND','Smart-order draft not found');const existing=await SmartOrder.findOne({draftId:draft._id});if(existing)return existing;if(draft.status!=='AWAITING_CONFIRMATION')throw new AppError(409,'GTT_DRAFT_NOT_CONFIRMABLE','Smart-order draft is not confirmable');if(draft.expiresAt<new Date()){draft.status='EXPIRED';await draft.save();throw new AppError(409,'GTT_DRAFT_EXPIRED','Smart-order draft expired');}if(hash(token)!==draft.confirmationNonceHash)throw new AppError(401,'INVALID_CONFIRMATION_TOKEN','Confirmation token is invalid');if(hash(canonical(terms(draft)))!==draft.payloadHash)throw new AppError(409,'GTT_DRAFT_CHANGED','Smart-order terms changed after preview');if(draft.mode==='LIVE')liveGate(userId);if(draft.quantity>env.LIVE_MAX_ORDER_QUANTITY||draft.quantity*Number(draft.postTriggerPrice??draft.triggerPrice)>env.LIVE_MAX_ORDER_NOTIONAL)throw new AppError(409,'ORDER_LIMIT_CHANGED','Smart order exceeds current safety limits');if(draft.transactionType==='SELL')await validateSellEligibility(userId,draft.instrumentId,draft.quantity,draft.mode,draft.symbol);draft.status='CONFIRMED';await draft.save();await Promise.all([event(userId,'GTT_CONFIRMED',undefined,draft._id),audit(userId,'GTT_CONFIRMED','SMART_ORDER_DRAFT',draft._id,{mode:draft.mode})]);try{const result=await brokerForMode(draft.mode).createSmartOrder({...terms(draft),referenceId:draft.idempotencyReference});const smart=await SmartOrder.findOneAndUpdate({draftId:draft._id},{$setOnInsert:{userId,draftId:draft._id,instrumentId:draft.instrumentId,symbol:draft.symbol,exchange:draft.exchange,transactionType:draft.transactionType,quantity:draft.quantity,triggerPrice:draft.triggerPrice,triggerDirection:draft.triggerDirection,postTriggerOrderType:draft.postTriggerOrderType,postTriggerPrice:draft.postTriggerPrice,product:draft.product,segment:draft.segment,mode:draft.mode,provider:draft.mode==='LIVE'?'GROWW':'PAPER',status:'ACTIVE',expiresAt:draft.validUntil,idempotencyReference:draft.idempotencyReference,brokerSmartOrderId:result.brokerSmartOrderId}},{upsert:true,new:true,setDefaultsOnInsert:true});draft.status='EXECUTED';await draft.save();await Promise.all([event(userId,'GTT_SUBMITTED',smart._id,draft._id,{provider:smart.provider}),audit(userId,'GTT_SUBMITTED','SMART_ORDER',smart._id,{provider:smart.provider,mode:smart.mode})]);return smart;}catch(error){draft.status='FAILED';await draft.save();await event(userId,'GTT_FAILED',undefined,draft._id);throw error;}
}

export async function evaluatePaperSmartOrders(clock:ClockContext={mode:'LIVE',asOf:new Date()},userId?:string){
  if(clock.mode==='REPLAY')return[];const active:any[]=await SmartOrder.find({mode:'PAPER',status:'ACTIVE',...(userId?{userId}:{})});const triggered:any[]=[];for(const item of active){if(item.expiresAt&&item.expiresAt<=clock.asOf){item.status='EXPIRED';await item.save();continue;}const quote:any=await MarketObservation.findOne({instrumentId:item.instrumentId,observedAt:{$lte:clock.asOf},availableAt:{$lte:clock.asOf}}).sort({observedAt:-1}).lean();if(!quote||quote.freshness==='STALE')continue;const hit=item.triggerDirection==='UP'?Number(quote.price)>=item.triggerPrice:Number(quote.price)<=item.triggerPrice;if(!hit)continue;const claimed:any=await SmartOrder.findOneAndUpdate({_id:item._id,status:'ACTIVE'},{$set:{status:'TRIGGERED',triggeredAt:clock.asOf}},{new:true});if(!claimed)continue;try{if(claimed.transactionType==='SELL'){const holding:any=await PaperHolding.findOne({userId:claimed.userId,instrumentId:claimed.instrumentId});if(!holding||holding.quantity<claimed.quantity)throw new AppError(409,'INSUFFICIENT_HOLDINGS','SELL quantity exceeds paper holdings');}const request:any={instrumentId:String(claimed.instrumentId),tradingSymbol:claimed.symbol,exchange:'NSE',segment:'CASH',product:'CNC',transactionType:claimed.transactionType,quantity:claimed.quantity,orderType:claimed.postTriggerOrderType,price:claimed.postTriggerPrice,validity:'DAY',referenceId:`${claimed.idempotencyReference}:trigger`,quote};const result=await brokerForMode('PAPER').createOrder(request);const order:any=await Order.findOneAndUpdate({smartOrderId:claimed._id},{$setOnInsert:{userId:claimed.userId,smartOrderId:claimed._id,provider:'PAPER',brokerOrderId:result.brokerOrderId,referenceId:request.referenceId,instrument:{id:claimed.instrumentId,symbol:claimed.symbol,exchange:'NSE'},side:claimed.transactionType,quantity:claimed.quantity,orderType:claimed.postTriggerOrderType,price:claimed.postTriggerPrice,product:'CNC',segment:'CASH',validity:'DAY',mode:'PAPER',status:result.status,filledQuantity:result.filledQuantity??0,averageFillPrice:result.averageFillPrice,submittedAt:clock.asOf,updatedBrokerAt:new Date()}},{upsert:true,new:true,setDefaultsOnInsert:true});claimed.linkedOrderId=order._id;await claimed.save();await Promise.all([event(String(claimed.userId),'GTT_TRIGGERED',claimed._id,claimed.draftId,{price:quote.price,orderId:order._id}),OrderEvent.create({userId:claimed.userId,orderId:order._id,type:'ORDER_SUBMITTED',recordedAt:new Date(),metadata:{source:'GTT_AGENT'}})]);if(order.status==='FILLED'){await OrderEvent.create({userId:claimed.userId,orderId:order._id,type:'FILLED',recordedAt:new Date(),metadata:{filledQuantity:order.filledQuantity,averageFillPrice:order.averageFillPrice}});await applyPaperFill(order);}triggered.push(claimed);}catch(error:any){claimed.status='FAILED';await claimed.save();await event(String(claimed.userId),'GTT_FAILED',claimed._id,claimed.draftId,{code:error?.code??'GTT_EXECUTION_FAILED'});}}
  return triggered;
}

export async function cancelSmartOrder(userId:string,id:string){const smart:any=await SmartOrder.findOne({_id:id,userId});if(!smart)throw new AppError(404,'GTT_NOT_FOUND','Smart order not found');if(smart.status!=='ACTIVE')throw new AppError(409,'GTT_NOT_CANCELLABLE','Only an active smart order can be cancelled');if(smart.mode==='LIVE')await brokerForMode('LIVE').cancelSmartOrder(smart);smart.status='CANCELLED';await smart.save();await Promise.all([event(userId,'GTT_CANCELLED',smart._id,smart.draftId),audit(userId,'GTT_CANCELLED','SMART_ORDER',smart._id,{mode:smart.mode})]);return smart;}
