import mongoose from 'mongoose'; import request from 'supertest'; import { afterAll,beforeAll,beforeEach,describe,expect,it } from 'vitest'; import { MongoMemoryServer } from 'mongodb-memory-server'; import { app } from '../src/app.js'; import { Instrument, MarketObservation } from '../src/models.js';
let mongo:MongoMemoryServer; let token=''; let watchlistId=''; let itemId=''; let instrumentId='';
beforeAll(async()=>{mongo=await MongoMemoryServer.create();await mongoose.connect(mongo.getUri());});
afterAll(async()=>{await mongoose.disconnect();await mongo.stop();});
beforeEach(async()=>{await mongoose.connection.db!.dropDatabase();const auth=await request(app).post('/api/v1/auth/register').send({name:'A User',email:'a@example.com',password:'secret123'});token=auth.body.token;const i=await Instrument.create({symbol:'TCS',name:'Tata Consultancy Services',exchange:'NSE',sector:'IT'});instrumentId=String(i._id);const w=await request(app).post('/api/v1/watchlists').set('Authorization',`Bearer ${token}`).send({name:'Core'});watchlistId=String(w.body.watchlist._id);const item=await request(app).post(`/api/v1/watchlists/${watchlistId}/items`).set('Authorization',`Bearer ${token}`).send({instrumentId});itemId=String(item.body.item._id);});
const auth=()=>({Authorization:`Bearer ${token}`});
describe('auth and normal watchlist integration',()=>{
 it('rejects duplicate registration and bad login',async()=>{expect((await request(app).post('/api/v1/auth/register').send({name:'Again',email:'a@example.com',password:'secret123'})).status).toBe(409);expect((await request(app).post('/api/v1/auth/login').send({email:'a@example.com',password:'wrong'})).status).toBe(401);});
 it('enforces auth and ownership',async()=>{expect((await request(app).get('/api/v1/watchlists')).status).toBe(401);const b=await request(app).post('/api/v1/auth/register').send({name:'Other',email:'b@example.com',password:'secret123'});expect((await request(app).get(`/api/v1/watchlists/${watchlistId}`).set('Authorization',`Bearer ${b.body.token}`)).status).toBe(404);});
 it('prevents duplicate items and supports search',async()=>{expect((await request(app).post(`/api/v1/watchlists/${watchlistId}/items`).set(auth()).send({instrumentId})).status).toBe(409);const r=await request(app).get('/api/v1/instruments/search?q=TC').set(auth());expect(r.body.instruments[0].symbol).toBe('TCS');});
 it('returns persisted admissible market data with all time fields',async()=>{const asOf=new Date('2025-01-10T12:00:00Z');await MarketObservation.create({instrumentId,source:'TEST',price:100,dayChange:2,dayChangePct:2,observedAt:asOf,ingestedAt:asOf,availableAt:asOf,provider:'TEST',freshness:'FRESH',adjustmentStatus:'SAFE'});const r=await request(app).get(`/api/v1/watchlists/${watchlistId}/market?clock=${encodeURIComponent(JSON.stringify({mode:'REPLAY',asOf}))}`).set(auth());expect(r.body.items[0]).toMatchObject({symbol:'TCS',latestPrice:100,dayChangePct:2,provider:'TEST'});expect(r.body.items[0].availableAt).toBeTruthy();});
});
describe('intent, replay and bounded agent integration',()=>{
 it('persists raw intent and asks for clarification without inventing values',async()=>{const r=await request(app).post(`/api/v1/watchlists/${watchlistId}/items/${itemId}/intents`).set(auth()).send({rawText:'TCS should participate when IT rallies'});expect(r.status).toBe(201);expect(r.body.intent.rawText).toBe('TCS should participate when IT rallies');expect(r.body.compiler.status).toBe('NEEDS_CLARIFICATION');});
 it('creates and advances an owned replay session',async()=>{const r=await request(app).post('/api/v1/replay/sessions').set(auth()).send({watchlistId,asOf:'2025-01-10T00:00:00Z'});expect(r.status).toBe(201);const advanced=await request(app).post(`/api/v1/replay/sessions/${r.body.session._id}/advance`).set(auth()).send({asOf:'2025-01-13T00:00:00Z'});expect(advanced.body.session.asOf.slice(0,10)).toBe('2025-01-13');});
 it('agent requires confirmation before creation and rejects trading requests',async()=>{const s=await request(app).post('/api/v1/watch-agent/sessions').set(auth()).send({watchlistId,watchlistItemId:itemId});const bad=await request(app).post(`/api/v1/watch-agent/sessions/${s.body.session._id}/message`).set(auth()).send({text:'Should I buy TCS?'});expect(bad.body.response.status).toBe('UNSUPPORTED');const no=await request(app).post(`/api/v1/watch-agent/sessions/${s.body.session._id}/confirm`).set(auth()).send({});expect(no.status).toBe(409);});
});
describe('expectation evidence integration',()=>{
 const observation=async(price:number,at:string,availableAt=at)=>MarketObservation.create({instrumentId,source:'TEST',price,close:price,dayChange:0,dayChangePct:0,observedAt:new Date(at),ingestedAt:new Date(at),availableAt:new Date(availableAt),provider:'TEST',freshness:'FRESH',adjustmentStatus:'SAFE'});
 it('resolves a threshold deterministically from safe admissible closes',async()=>{await observation(100,'2025-01-06T00:00:00Z');await observation(120,'2025-01-07T00:00:00Z');const e=await request(app).post(`/api/v1/watchlists/${watchlistId}/items/${itemId}/expectations`).set(auth()).send({template:'PRICE_THRESHOLD',direction:'ABOVE',threshold:110,deadlineTradingDays:1,clock:{mode:'REPLAY',asOf:'2025-01-06T00:00:00Z'}});expect(e.status).toBe(201);const resolved=await request(app).post(`/api/v1/expectations/${e.body.expectation._id}/resolve`).set(auth()).send({clock:{mode:'REPLAY',asOf:'2025-01-07T00:00:00Z'}});expect(resolved.body.expectation.resolution.outcome).toBe('CONFIRMED');const repeated=await request(app).post(`/api/v1/expectations/${e.body.expectation._id}/resolve`).set(auth()).send({clock:{mode:'REPLAY',asOf:'2025-01-07T00:00:00Z'}});expect(repeated.body.expectation.resolution.outcome).toBe('CONFIRMED');});
 it('does not reveal a future-available observation in a past replay timeline',async()=>{await observation(100,'2025-01-06T00:00:00Z');const e=await request(app).post(`/api/v1/watchlists/${watchlistId}/items/${itemId}/expectations`).set(auth()).send({template:'PRICE_THRESHOLD',direction:'ABOVE',threshold:110,deadlineTradingDays:1,clock:{mode:'REPLAY',asOf:'2025-01-06T00:00:00Z'}});await observation(150,'2025-01-07T00:00:00Z','2025-01-08T00:00:00Z');const timeline=await request(app).get(`/api/v1/expectations/${e.body.expectation._id}/timeline?clock=${encodeURIComponent(JSON.stringify({mode:'REPLAY',asOf:'2025-01-07T00:00:00Z'}))}`).set(auth());expect(timeline.body.timeline.some((x:any)=>x.instrument?.close===150)).toBe(false);});
});
