import mongoose from 'mongoose'; import request from 'supertest'; import { afterAll,beforeAll,beforeEach,describe,expect,it } from 'vitest'; import { MongoMemoryServer } from 'mongodb-memory-server'; import { app } from '../src/app.js'; import { Instrument, MarketObservation, NormalityContract } from '../src/models.js';
let mongo:MongoMemoryServer; let token=''; let watchlistId=''; let itemId=''; let instrumentId='';
beforeAll(async()=>{mongo=await MongoMemoryServer.create();await mongoose.connect(mongo.getUri());});
afterAll(async()=>{await mongoose.disconnect();await mongo.stop();});
beforeEach(async()=>{await mongoose.connection.db!.dropDatabase();const auth=await request(app).post('/api/v1/auth/register').send({name:'A User',email:'a@example.com',password:'secret123'});token=auth.body.token;const i=await Instrument.create({symbol:'TCS',name:'Tata Consultancy Services',exchange:'NSE',sector:'IT'});instrumentId=String(i._id);const w=await request(app).post('/api/v1/watchlists').set('Authorization',`Bearer ${token}`).send({name:'Core'});watchlistId=String(w.body.watchlist._id);const item=await request(app).post(`/api/v1/watchlists/${watchlistId}/items`).set('Authorization',`Bearer ${token}`).send({instrumentId});itemId=String(item.body.item._id);});
const auth=()=>({Authorization:`Bearer ${token}`});
describe('auth and normal watchlist integration',()=>{
 it('rejects duplicate registration and bad login',async()=>{expect((await request(app).post('/api/v1/auth/register').send({name:'Again',email:'a@example.com',password:'secret123'})).status).toBe(409);expect((await request(app).post('/api/v1/auth/login').send({email:'a@example.com',password:'wrong'})).status).toBe(401);});
 it('enforces auth and ownership',async()=>{expect((await request(app).get('/api/v1/watchlists')).status).toBe(401);const b=await request(app).post('/api/v1/auth/register').send({name:'Other',email:'b@example.com',password:'secret123'});expect((await request(app).get(`/api/v1/watchlists/${watchlistId}`).set('Authorization',`Bearer ${b.body.token}`)).status).toBe(404);});
 it('prevents duplicate items and supports search',async()=>{expect((await request(app).post(`/api/v1/watchlists/${watchlistId}/items`).set(auth()).send({instrumentId})).status).toBe(409);const r=await request(app).get('/api/v1/instruments/search?q=TC').set(auth());expect(r.body.instruments[0].symbol).toBe('TCS');});
 it('returns persisted admissible market data with all time fields',async()=>{const asOf=new Date('2025-01-10T12:00:00Z');await MarketObservation.create({instrumentId,source:'TEST',price:100,dayChange:2,dayChangePct:2,observedAt:asOf,ingestedAt:asOf,availableAt:asOf,provider:'TEST',freshness:'FRESH',adjustmentStatus:'SAFE'});const r=await request(app).get(`/api/v1/watchlists/${watchlistId}/market?clock=${encodeURIComponent(JSON.stringify({mode:'REPLAY',asOf}))}`).set(auth());expect(r.body.items[0]).toMatchObject({symbol:'TCS',latestPrice:100,dayChangePct:2,provider:'TEST'});expect(r.body.items[0].availableAt).toBeTruthy();});
});
describe('intent, replay and bounded agent integration',()=>{
 it('persists raw intent and asks for clarification without inventing values',async()=>{const r=await request(app).post(`/api/v1/watchlists/${watchlistId}/items/${itemId}/intents`).set(auth()).send({rawText:'TCS should participate when IT rallies'});expect(r.status).toBe(201);expect(r.body.intent.rawText).toBe('TCS should participate when IT rallies');expect(r.body.compiler.status).toBe('NEEDS_CLARIFICATION');});
 it('creates and advances an owned replay session',async()=>{const r=await request(app).post('/api/v1/replay/sessions').set(auth()).send({watchlistId,asOf:'2025-01-10T00:00:00Z'});expect(r.status).toBe(201);const advanced=await request(app).post(`/api/v1/replay/sessions/${r.body.session._id}/advance`).set(auth()).send({asOf:'2025-01-13T00:00:00Z'});expect(advanced.body.session.asOf.slice(0,10)).toBe('2025-01-13');});
 it('serves dashboard, brief, and history from the server-owned replay clock',async()=>{const r=await request(app).post('/api/v1/replay/sessions').set(auth()).send({watchlistId,asOf:'2025-01-10T00:00:00Z'});const base=`/api/v1/replay/sessions/${r.body.session._id}`;const [dashboard,brief,history]=await Promise.all([request(app).get(`${base}/dashboard`).set(auth()),request(app).get(`${base}/brief`).set(auth()),request(app).get(`${base}/history`).set(auth())]);expect(dashboard.body.clock).toMatchObject({mode:'REPLAY',asOf:'2025-01-10T00:00:00.000Z'});expect(brief.body.clock.mode).toBe('REPLAY');expect(history.body.clock.mode).toBe('REPLAY');});
 it('agent requires confirmation before creation and rejects trading requests',async()=>{const s=await request(app).post('/api/v1/watch-agent/sessions').set(auth()).send({watchlistId,watchlistItemId:itemId});const bad=await request(app).post(`/api/v1/watch-agent/sessions/${s.body.session._id}/message`).set(auth()).send({text:'Should I buy TCS?'});expect(bad.body.response.status).toBe('UNSUPPORTED');const no=await request(app).post(`/api/v1/watch-agent/sessions/${s.body.session._id}/confirm`).set(auth()).send({});expect(no.status).toBe(409);});
});
describe('expectation evidence integration',()=>{
 const observation=async(price:number,at:string,availableAt=at)=>MarketObservation.create({instrumentId,source:'TEST',price,close:price,dayChange:0,dayChangePct:0,observedAt:new Date(at),ingestedAt:new Date(at),availableAt:new Date(availableAt),provider:'TEST',freshness:'FRESH',adjustmentStatus:'SAFE'});
 it('resolves a threshold deterministically from safe admissible closes',async()=>{await observation(100,'2025-01-06T00:00:00Z');await observation(120,'2025-01-07T00:00:00Z');const e=await request(app).post(`/api/v1/watchlists/${watchlistId}/items/${itemId}/expectations`).set(auth()).send({template:'PRICE_THRESHOLD',direction:'ABOVE',threshold:110,deadlineTradingDays:1,clock:{mode:'REPLAY',asOf:'2025-01-06T00:00:00Z'}});expect(e.status).toBe(201);const resolved=await request(app).post(`/api/v1/expectations/${e.body.expectation._id}/resolve`).set(auth()).send({clock:{mode:'REPLAY',asOf:'2025-01-07T00:00:00Z'}});expect(resolved.body.expectation.resolution.outcome).toBe('CONFIRMED');const repeated=await request(app).post(`/api/v1/expectations/${e.body.expectation._id}/resolve`).set(auth()).send({clock:{mode:'REPLAY',asOf:'2025-01-07T00:00:00Z'}});expect(repeated.body.expectation.resolution.outcome).toBe('CONFIRMED');});
 it('does not reveal a future-available observation in a past replay timeline',async()=>{await observation(100,'2025-01-06T00:00:00Z');const e=await request(app).post(`/api/v1/watchlists/${watchlistId}/items/${itemId}/expectations`).set(auth()).send({template:'PRICE_THRESHOLD',direction:'ABOVE',threshold:110,deadlineTradingDays:1,clock:{mode:'REPLAY',asOf:'2025-01-06T00:00:00Z'}});await observation(150,'2025-01-07T00:00:00Z','2025-01-08T00:00:00Z');const timeline=await request(app).get(`/api/v1/expectations/${e.body.expectation._id}/timeline?clock=${encodeURIComponent(JSON.stringify({mode:'REPLAY',asOf:'2025-01-07T00:00:00Z'}))}`).set(auth());expect(timeline.body.timeline.some((x:any)=>x.instrument?.close===150)).toBe(false);});
 it('uses the first benchmark trigger even when the final return falls below it',async()=>{const benchmark=await Instrument.create({symbol:'NIFTYIT',name:'NIFTY IT',exchange:'NSE',sector:'INDEX'});const add=async(id:any,price:number,at:string)=>MarketObservation.create({instrumentId:id,source:'TEST',price,close:price,observedAt:new Date(at),ingestedAt:new Date(at),availableAt:new Date(at),provider:'TEST',freshness:'FRESH',adjustmentStatus:'SAFE'});await add(instrumentId,100,'2025-01-06');await add(benchmark._id,100,'2025-01-06');await add(benchmark._id,104,'2025-01-07');await add(benchmark._id,101,'2025-01-08');await add(instrumentId,103,'2025-01-08');const e=await request(app).post(`/api/v1/watchlists/${watchlistId}/items/${itemId}/expectations`).set(auth()).send({template:'BENCHMARK_PARTICIPATION',benchmarkInstrumentId:String(benchmark._id),benchmarkTriggerPct:3,minimumParticipationRatio:.5,deadlineTradingDays:2,clock:{mode:'REPLAY',asOf:'2025-01-06'}});const r=await request(app).post(`/api/v1/expectations/${e.body.expectation._id}/resolve`).set(auth()).send({clock:{mode:'REPLAY',asOf:'2025-01-08'}});expect(r.body.expectation.resolution.outcome).toBe('CONFIRMED');expect(r.body.expectation.resolution.measurement.benchmarkReturnAtTrigger).toBeCloseTo(4);expect(r.body.expectation.resolution.measurement.triggerObservedAt.slice(0,10)).toBe('2025-01-07');});
});
describe('normality contract and safe paper order integration',()=>{
 it('automatically seals a contract and primary dependency when a stock is added',async()=>{const contract=await NormalityContract.findOne({watchlistItemId:itemId}).lean();expect(contract).toBeTruthy();expect(contract?.basisHash).toMatch(/^[a-f\d]{64}$/);expect(contract?.windowTradingDays).toBe(20);});
 it('requires explicit confirmation and makes retry idempotent',async()=>{const now=new Date();await MarketObservation.create({instrumentId,source:'TEST',price:100,dayChange:1,dayChangePct:1,observedAt:now,ingestedAt:now,availableAt:now,provider:'TEST',freshness:'FRESH',adjustmentStatus:'SAFE'});const d=await request(app).post('/api/v1/orders/drafts').set(auth()).send({instrumentId,transactionType:'BUY',quantity:1,orderType:'MARKET',mode:'PAPER'});expect(d.status).toBe(201);expect((await request(app).get('/api/v1/orders').set(auth())).body.orders).toHaveLength(0);const c=await request(app).post(`/api/v1/orders/${d.body.draft._id}/confirm`).set(auth()).send({confirmationToken:d.body.confirmationToken});expect(c.body.order.status).toBe('FILLED');expect(c.body.order.mode).toBe('PAPER');const retry=await request(app).post(`/api/v1/orders/${d.body.draft._id}/confirm`).set(auth()).send({confirmationToken:d.body.confirmationToken});expect(retry.body.order._id).toBe(c.body.order._id);});
 it('rejects invalid confirmation and cross-user access',async()=>{const now=new Date();await MarketObservation.create({instrumentId,source:'TEST',price:100,dayChange:1,dayChangePct:1,observedAt:now,ingestedAt:now,availableAt:now,provider:'TEST',freshness:'FRESH',adjustmentStatus:'SAFE'});const d=await request(app).post('/api/v1/orders/drafts').set(auth()).send({instrumentId,transactionType:'BUY',quantity:1,orderType:'MARKET',mode:'PAPER'});expect((await request(app).post(`/api/v1/orders/${d.body.draft._id}/confirm`).set(auth()).send({confirmationToken:'this-token-is-definitely-invalid'})).status).toBe(401);const other=await request(app).post('/api/v1/auth/register').send({name:'Other',email:'orders@example.com',password:'secret123'});expect((await request(app).get(`/api/v1/orders/drafts/${d.body.draft._id}`).set('Authorization',`Bearer ${other.body.token}`)).status).toBe(404);});
 it('exposes dashboard and append-only audit history',async()=>{expect((await request(app).get('/api/v1/dashboard/overview').set(auth())).body.watchlistsCount).toBe(1);const h=await request(app).get('/api/v1/history').set(auth());expect(h.status).toBe(200);});
});
