import { env } from '../../config/env.js'; import type { ClockContext } from '../../shared/clock.js'; import { AppError } from '../../shared/errors.js';
export type Quote = { instrumentId: string; symbol?:string; price: number; dayChange: number; dayChangePct: number; observedAt: Date; ingestedAt: Date; availableAt: Date; provider: string; freshness: 'FRESH'|'DELAYED'|'STALE'; adjustmentStatus: 'SAFE'|'UNSAFE'|'UNKNOWN' };
export type Bar = Quote & { open: number; high: number; low: number; close: number; adjustedClose?: number; volume?: number };
export interface MarketDataProvider { getQuote(instrument: { _id: unknown; symbol: string }, clock: ClockContext): Promise<Quote>; getQuotes(instruments: { _id: unknown; symbol: string }[], clock: ClockContext): Promise<Quote[]>; getHistoricalBars(instrument: { _id: unknown; symbol: string }, from: Date, to: Date, clock: ClockContext): Promise<Bar[]>; health(): Promise<'UP'|'DOWN'|'UNCONFIGURED'>; }
export class TwelveDataProvider implements MarketDataProvider {
  private requireKey() { if (!env.TWELVE_DATA_API_KEY) throw new AppError(503, 'MARKET_UNAVAILABLE', 'Market provider is not configured'); return env.TWELVE_DATA_API_KEY; }
  private async request(path: string, params: Record<string,string>) { const u = new URL(path, env.TWELVE_DATA_BASE_URL); Object.entries({ ...params, apikey: this.requireKey() }).forEach(([k,v]) => u.searchParams.set(k,v)); let response: Response; try { response = await fetch(u); } catch { throw new AppError(502, 'MARKET_PROVIDER_ERROR', 'Market provider request failed'); } if (response.status === 401 || response.status === 403) throw new AppError(503, 'MARKET_AUTH_ERROR', 'Market provider credentials were rejected'); if (response.status === 429) throw new AppError(503, 'MARKET_RATE_LIMITED', 'Market provider rate limit reached'); if (!response.ok) throw new AppError(502, 'MARKET_PROVIDER_ERROR', 'Market provider returned an error'); const body = await response.json() as any; if (body.status === 'error') throw new AppError(502, 'MARKET_PROVIDER_ERROR', body.message || 'Market provider returned an error'); return body; }
  async getQuote(i: { _id: unknown; symbol: string }, clock: ClockContext): Promise<Quote> { if (clock.mode === 'REPLAY') throw new AppError(400, 'REPLAY_REQUIRES_STORED_DATA', 'Replay only reads previously observed market data'); const x = await this.request('/quote', { symbol: i.symbol }); const observedAt = new Date(x.datetime); if(Number.isNaN(observedAt.getTime())||!Number.isFinite(Number(x.close)))throw new AppError(502,'MARKET_INVALID_DATA','Market provider returned incomplete quote data'); const ingestedAt=new Date(); const age = ingestedAt.getTime() - observedAt.getTime(); return { instrumentId: String(i._id),symbol:i.symbol, price: Number(x.close), dayChange: Number(x.change), dayChangePct: Number(x.percent_change), observedAt, ingestedAt, availableAt:ingestedAt, provider: 'TWELVE_DATA', freshness: age < 10*60_000 ? 'FRESH' : age < 24*60*60_000 ? 'DELAYED' : 'STALE', adjustmentStatus: 'UNKNOWN' }; }
  async getQuotes(instruments:{_id:unknown;symbol:string}[],clock:ClockContext){return Promise.all(instruments.map(i=>this.getQuote(i,clock)));}
  async getHistoricalBars(i: { _id: unknown; symbol: string }, from: Date, to: Date, clock: ClockContext): Promise<Bar[]> { if (clock.mode === 'REPLAY') throw new AppError(400, 'REPLAY_REQUIRES_STORED_DATA', 'Replay only reads stored data'); const x = await this.request('/time_series', { symbol: i.symbol, interval: '1day', start_date: from.toISOString().slice(0,10), end_date: to.toISOString().slice(0,10) }); const ingestedAt=new Date(); return (x.values || []).map((v: any) => ({ instrumentId: String(i._id),symbol:i.symbol, price: Number(v.close), dayChange: 0, dayChangePct: 0, observedAt: new Date(v.datetime), ingestedAt, availableAt:ingestedAt, provider: 'TWELVE_DATA', freshness: 'DELAYED', adjustmentStatus: 'UNKNOWN', open: Number(v.open), high: Number(v.high), low: Number(v.low), close: Number(v.close), volume: Number(v.volume) })).sort((a:Bar,b:Bar)=>a.observedAt.getTime()-b.observedAt.getTime()); }
  async health() { return env.TWELVE_DATA_API_KEY ? 'UP' : 'UNCONFIGURED'; }
}
